databases:
  - name: payout-db
    databaseName: payouts_db
    user: postgres
    plan: free

services:
  - type: redis
    name: payout-redis
    plan: free
    ipAllowList: []

  - type: web
    name: payout-engine-api
    runtime: docker
    plan: free
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    healthCheckPath: /api/v1/health/
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: payout-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: payout-redis
          type: redis
          property: connectionString
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "*"
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: FRONTEND_URL
        value: "https://payout-engine.vercel.app"
      - key: CORS_ALLOWED_ORIGINS
        value: "https://payout-engine.vercel.app"

  - type: worker
    name: payout-engine-celery-worker
    runtime: docker
    plan: free
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    dockerCommand: celery -A payouts_engine worker -l info --concurrency=2
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: payout-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: payout-redis
          type: redis
          property: connectionString

  - type: worker
    name: payout-engine-celery-beat
    runtime: docker
    plan: free
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    dockerCommand: celery -A payouts_engine beat -l info
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: payout-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: payout-redis
          type: redis
          property: connectionString
